const JSON_INDENT_SPACES = 2;
const JSON_INDENT_SPACES_MULTIPLY = 5;
const RADIX_TEN = 10;
const SECONDS_PER_MINUTE = 60;
const RATE_LIMIT_MAX = 100;
const MIN_API_KEY_LENGTH = 10;
const MIN_JWT_SECRET_LENGTH = 32;
const MIN_RATE_LIMIT_WINDOW_MS = 900000;
const LATENCY_THRESHOLD = 100;
const MATH_ROUND_DIVIDE = 1024;
const MEMORY_USAGE_THRESHOLD = 500;
const HEALTH_CHECK_INTERVAL_MS_FIVE = 5;
const HEALTH_CHECK_INTERVAL_MS_SIXTY = 60;
const HEALTH_CHECK_INTERVAL_MS_ONE_HUNDRED = 1000;
const SHUTDOWN_DELAY_MS = 1000;
const FORCE_SHUTDOWN_TIMEOUT_MS = 10000;
const SERVER_STARTUP_RETRY_DELAY = 5000;
const SERVER_STARTUP_MAX_RETRIES = 5;
const ONE_DAY_MS_TWENTY_FOUR = 24;
const ONE_DAY_MS_HOUR = 60;
const ONE_DAY_MS_MINUTE = 60;
const ONE_DAY_MS_SECOND = 1000;
const ONE_DAY_MS = ONE_DAY_MS_TWENTY_FOUR * ONE_DAY_MS_HOUR * ONE_DAY_MS_MINUTE * ONE_DAY_MS_SECOND;

const NUMERIC_CONSTANTS = {
  JSON_INDENT_SPACES,
  RADIX_TEN,
  SECONDS_PER_MINUTE,
  RATE_LIMIT_MAX,
  MIN_API_KEY_LENGTH,
  MIN_JWT_SECRET_LENGTH,
  MIN_RATE_LIMIT_WINDOW_MS,
  JSON_INDENT_SPACES_MULTIPLY,
  LATENCY_THRESHOLD,
  MATH_ROUND_DIVIDE,
  MEMORY_USAGE_THRESHOLD,
  HEALTH_CHECK_INTERVAL_MS_FIVE,
  HEALTH_CHECK_INTERVAL_MS_SIXTY,
  HEALTH_CHECK_INTERVAL_MS_ONE_HUNDRED,
  SHUTDOWN_DELAY_MS,
  FORCE_SHUTDOWN_TIMEOUT_MS,
  SERVER_STARTUP_RETRY_DELAY,
  SERVER_STARTUP_MAX_RETRIES,
  ONE_DAY_MS,
} as const;

Object.freeze(NUMERIC_CONSTANTS);

export { NUMERIC_CONSTANTS };
